### ISSUE TITLE
Parameter public_ip_dns actually optional?

### ISSUE THREAD

**Issue by horsey** [Azure/terraform-azurerm-compute#49] opened 2018-01-24 20:51 UTC
Hello,
 The ```public_ip_dns``` parameter  that is translated to  ```domain_name_label``` parameter  for the resource ```azurerm_public_ip```  in the compute module is actually optional according to the Terraform  documentation: 

https://www.terraform.io/docs/providers/azurerm/r/public_ip.html

The compute module makes this mandatory for some reason.

**Comment by metacpp** [comment] 2018-10-01 23:36
@horsey Thanks for opening this issue. Since it's not reproduced any more, I will close it.

**Comment by imiric** [comment] 2018-10-30 12:14
Hi, I'm still running into this issue, even on latest `master` commit (e9b43630cf):

```
$ terraform providers                                                                             
.
├── module.network
│   └── provider.azurerm
└── module.servers
    ├── provider.azurerm >= 1.1.0
    ├── provider.random ~> 1.0
    └── module.os
```

Sample main.tf:
```
module "servers" {
  source               = "git::https://github.com/Azure/terraform-azurerm-compute.git?ref=e9b43630cf0a36da3806bd3dbaf91063b016a047"
  resource_group_name  = "${var.prefix}-resources"
  location             = "${var.location}"
  vm_os_publisher      = "Canonical"
  vm_os_offer          = "UbuntuServer"
  vm_os_sku            = "16.04-LTS"
  vm_size              = "Standard_NC6"
  vm_hostname          = "myhostname"
  nb_instances         = "3"
  nb_public_ip         = "3"
  remote_port          = "22"
  delete_os_disk_on_termination = true
  admin_username       = "adminuser"
  ssh_key              = "key.pub"
  data_disk            = "true"
  data_disk_size_gb    = "500"
  storage_account_type = "Standard_LRS"
  vnet_subnet_id       = "${module.network.vnet_subnets[0]}"
  tags                 = "${var.tags}"
}

module "network" {
  source               = "Azure/network/azurerm"
  version              = "~> 1.1.1"
  location             = "${var.location}"
  allow_ssh_traffic    = "true"
  resource_group_name  = "${var.prefix}-resources"
}

output "vm_public_ips" {
  value = "${module.servers.public_ip_address}"
}
```

Running `terraform apply` results in `Error: module.servers.azurerm_public_ip.vm[0]: "domain_name_label" cannot be an empty string: ""`. The same thing happens if specifying `public_ip_dns = ["", "", ""]`.

Am I missing something? Thanks.

**Comment by metacpp** [comment] 2018-12-11 21:58
@imiric thanks for providing details here. @JunyiYi : can you take a look at it to double confirm ?

**Comment by JunyiYi** [comment] 2018-12-14 01:21
This issue is caused by a breaking change of not accepting empty strings any more in Azure provider: https://github.com/terraform-providers/terraform-provider-azurerm/blob/22ca0989ab65278b202677740dfbc7373b2ae82a/azurerm/helpers/validate/public_ip.go#L8.

**Closed** 2020-03-10 06:46 UTC
Labels: bug, microsoft/P2
